name: Lint and Format Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: Run Flake8
        run: |
          poetry run flake8 .
      - name: Run Black
        run: |
          poetry run black --check .